import { Resource } from "../models/resource.model";

export let resources: Resource[] = [
  {
    id: 1,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 2,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 3,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 4,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 5,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 6,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 7,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 8,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 9,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 10,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 11,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 12,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 13,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 14,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 15,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 16,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 17,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 18,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 19,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 20,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 21,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 22,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 23,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 24,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 25,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 26,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 27,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 28,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 29,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 30,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 31,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 32,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
  {
    id: 33,
    title: 'Super 1',
    description: 'Super description 1',
    bookable: true,
    info1: 'Pin: 3303',
    info2: '',
    info3: '',
    info4: '',
    info5: '',
    remoteAccess: false,
  },
];