import { Slot } from '../models/slot.model';

export let slots: Slot[] = [
  {
    id: 1,
    title: 'Slot 1',
    dateStart: new Date(),
    dateEnd: new Date(),
    free: false,
    note: '',
    resource: {
      id: 33,
      title: 'Super 1',
      description: 'Super description 1',
      bookable: true,
      info1: 'Pin: 3303',
      info2: '',
      info3: '',
      info4: '',
      info5: '',
      remoteAccess: false,
    },
  },
  {
    id: 2,
    title: 'Slot 1',
    dateStart: new Date(),
    dateEnd: new Date(),
    free: false,
    note: '',
    resource: {
      id: 33,
      title: 'Super 1',
      description: 'Super description 1',
      bookable: true,
      info1: 'Pin: 3303',
      info2: '',
      info3: '',
      info4: '',
      info5: '',
      remoteAccess: false,
    },
  },
  {
    id: 3,
    title: 'Slot 1',
    dateStart: new Date(),
    dateEnd: new Date(),
    free: false,
    note: '',
    resource: {
      id: 33,
      title: 'Super 1',
      description: 'Super description 1',
      bookable: true,
      info1: 'Pin: 3303',
      info2: '',
      info3: '',
      info4: '',
      info5: '',
      remoteAccess: false,
    },
  },
];
